# Generated by Django 2.2.7 on 2019-12-18 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioMeditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('time', models.PositiveIntegerField()),
                ('author', models.CharField(max_length=150)),
                ('image_source', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MeditationCatagoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MeditationCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('image_uri', models.TextField()),
                ('audio_meditations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.AudioMeditation')),
                ('catagories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.MeditationCatagoryType')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='user_favourite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
