# Generated by Django 3.0.1 on 2019-12-21 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeditationCatagoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserCatagories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_meditation_type_catagories', models.ManyToManyField(to='data.MeditationCatagoryType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeditationCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('image_uri', models.TextField()),
                ('catagories', models.ManyToManyField(to='data.MeditationCatagoryType')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='user_favourite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudioMeditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('time', models.PositiveIntegerField()),
                ('author', models.CharField(max_length=150)),
                ('image_source', models.TextField()),
                ('audio_uri', models.TextField(blank=True, default=None, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.MeditationCourse')),
            ],
        ),
    ]
