# Generated by Django 3.0.1 on 2019-12-21 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meditationcourse',
            name='audio_meditations',
        ),
        migrations.AddField(
            model_name='audiomeditation',
            name='audio_uri',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='audiomeditation',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.MeditationCourse'),
        ),
        migrations.RemoveField(
            model_name='meditationcourse',
            name='catagories',
        ),
        migrations.AddField(
            model_name='meditationcourse',
            name='catagories',
            field=models.ManyToManyField(to='data.MeditationCatagoryType'),
        ),
        migrations.CreateModel(
            name='UserCatagories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_meditation_type_catagories', models.ManyToManyField(to='data.MeditationCatagoryType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
