# Generated by Django 3.0.1 on 2020-01-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
