# Generated by Django 3.0.1 on 2020-01-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_directmessage_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFeelings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depressed', models.PositiveIntegerField(default=0)),
                ('anxious', models.PositiveIntegerField(default=0)),
                ('lost', models.PositiveIntegerField(default=0)),
                ('stressed', models.PositiveIntegerField(default=0)),
                ('excited', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
