# Generated by Django 3.0.1 on 2020-01-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_myfeelings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='mood',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
