# Generated by Django 3.0.2 on 2020-01-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_fitnessgoals'),
    ]

    operations = [
        migrations.CreateModel(
            name='audio_field_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audi_body', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
