# Generated by Django 3.0.2 on 2020-01-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20200112_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_field_test',
            name='audi_body',
            field=models.FileField(upload_to='media/documents'),
        ),
    ]
