# Generated by Django 3.0.1 on 2020-01-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20200112_1723'),
        ('data', '0016_auto_20200114_1349'),
    ]

    operations = [
    ]
