# Generated by Django 3.0.1 on 2020-01-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_merge_20200114_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditions',
            name='birth_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useradditions',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useradditions',
            name='gender',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='useradditions',
            name='height_feet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useradditions',
            name='height_inches',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useradditions',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
