# Generated by Django 2.2.7 on 2019-12-18 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meditationcourse',
            name='audio_meditations',
        ),
        migrations.AddField(
            model_name='audiomeditation',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.MeditationCourse'),
        ),
    ]
